### ISSUE TITLE
UI - bandeau bleu "ce site est encore très rudimentaire" trop visible....

### ISSUE THREAD

**Issue by MathildeBras** [mur-project/mur-web#5]
...par rapport à la description du projet en dessous

 Dans la ligne de flottaison sur mobile cela prend pas mal de place.

**Comment by cquest** [comment]
Il est temporaire... difficile de le réduire pour l'instant

**Comment by Solene-OSI** [comment]
Proposition de mise en forme et quelques changement de formulations : 
Aujourd’hui, le monde médical manque de respirateurs pour pouvoir travailler convenablement et sauver des vies .
En tant que citoyens, nous sommes tous concernés et nous pouvons agir concrètement !
Le nombre de lits disponibles en service de réanimation est très limité car les hôpitaux manquent de respirateurs. Pourtant ce matériel est nécessaire au corps médical afin de prodiguer des soins aux cas les plus aigus de la maladie Covid-19.
 
Pour les malades les plus critiques, un respirateur augmente leurs chances de survie par 5.
Notre objectif : Produire le maximum de respirateurs, le plus rapidement possible, pour sauver un maximum de vies.
 

14 mars 2020 : 
Conception d'un respirateur prototype "MUR" (Minimal Universal Respirator), fabriqué avec le moins d'éléments complexes possibles.
-	Certaines pièces (valves) par impression 3D
-	 Platines électroniques très courantes (Arduino)
-	Autres composants très courants aussi (boutons, potentiomètre, servo-moteurs de modélisme).


Les premiers essais sont très prometteurs, les courbes de pressions mesurées ont été jugées excellentes par plusieurs médecins réanimateurs avec qui l'équipe travaille. 
**Date de début** :
Nous entamons donc la phase de test sur banc d'essai avec la collaboration de l'AP-HP.

**Comment by cquest** [comment]
Corrigé
